create database employee;
use employee;
select EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT from emp_record_table;
select EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING from emp_record_table where EMP_RATING<2;
select EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING from emp_record_table where EMP_RATING>4;
select EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING from emp_record_table where EMP_RATING between 2 and 4;
select concat(FIRST_NAME,' ',LAST_NAME) as NAME from emp_record_table where dept="Finance";
select dept,count(emp_id) from emp_record_table group by dept;
select * from emp_record_table where dept="healthcare" union select * from emp_record_table where dept="finance";
select EMP_ID,FIRST_NAME,LAST_NAME,ROLE,DEPT,EMP_RATING,max(emp_rating) over(partition by dept) as Max_Rating from emp_record_table;
select role,min(salary),Max(salary) from emp_record_table group by role;
select *, rank() over(order by exp desc) as rnk from emp_record_table;
create view emp_country as (select * from emp_record_table where salary>6000);
select * from emp_country;
select * from emp_record_table where emp_id in (select emp_id from emp_record_table where exp>10);
alter table emp_record_table modify column first_name varchar(50);
describe emp_record_table;
create index id_first_name on emp_record_table(first_name);
show indexes from emp_record_table;
select * from emp_record_table where first_name = "Eric";
select *, (0.05*salary*EMP_RATING) as bonus from emp_record_table;
create view avgsalary as select COUNTRY, avg(salary) as Avg_salary from emp_record_table group by COUNTRY;
select * from avgsalary;
create view avgsalary2 as select CONTINENT, avg(salary) as Avg_salary from emp_record_table group by CONTINENT;
select * from avgsalary2;